# Generated by Django 6.0 on 2025-12-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_film_created_at_alter_film_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='reviews.genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
