# Generated by Django 6.0 on 2025-12-16 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_film_description_film_updated_at_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
