# Generated by Django 6.0 on 2025-12-16 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_remove_film_playlist_url_remove_film_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
